### ISSUE TITLE
关于使用Dialog组件与页面滚动的问题

### ISSUE THREAD

**Issue by CharmSun** [bizdevfe/biz-ui#29]
当Dialog组件不添加阻止滚动的代码，会出现  弹窗中的Select组件或日历组件 随页面滚动的情况；
当Dialog组件添加阻止滚动的代码后，仍然会有以下问题：
1. 当页面向下滚动到比较多时，弹窗就会出现遮罩下面内容无法显示的情况
2. 弹窗后，如果再弹窗，上面的弹窗关闭后，页面仍然能滚动

想到的可以解决的办法：
1. 更改网页布局，使用没有滚动条的满屏布局；治标不治本
2. 将Select组件，日历组件的定位改为相对于所在元素的父级；改动量会比较大，这样弹框下面的内容仍然能滚动

还有其他解决方案吗？？？

**Comment by tangjinzhou** [comment]
将dialog改成绝对定位，跟随滚动

**Comment by rickyleung** [comment]
1.4.0 将添加 position 参数：fixed、absolute，设为 'absolute' 可使 Dialog 内组件跟随滚动
